# Generated by Django 4.2.7 on 2023-11-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomeUser',
            new_name='CustomUser',
        ),
    ]
