# Generated by Django 4.2.7 on 2023-12-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='area',
            field=models.CharField(choices=[('AFTERMARKET', 'Aftermarket'), ('IT', 'IT'), ('ADMINISTRATION', 'Administration'), ('PRODUCTION', 'Production')], default='IT', max_length=255),
        ),
    ]
