# Generated by Django 4.2.7 on 2023-12-05 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_number', models.CharField(max_length=9, primary_key=True, serialize=False, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('USE', 'Use'), ('DISUSE', 'disuse'), ('IDLE', 'idle')], default='USE', max_length=9)),
                ('purchase_date', models.DateField()),
                ('warranty_expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('computer_id', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('drive_serialnumber', models.CharField(max_length=50)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assetsapp.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsapp.asset')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assetsapp.assetcategory'),
        ),
    ]
