# Generated by Django 4.2.7 on 2023-12-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0002_asset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('USE', 'use'), ('DISUSE', 'disuse'), ('IDLE', 'idle')], default='USE', max_length=9),
        ),
    ]
