# Generated by Django 4.2.7 on 2023-12-27 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assetsapp', '0003_alter_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('serialnumber', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('capacity', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='drive_serialnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetsapp.drive'),
        ),
    ]
