# Generated by Django 4.2.7 on 2023-12-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetsapp', '0004_drive_alter_computer_drive_serialnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='drive_serialnumber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetsapp.drive'),
        ),
    ]
